DROP DATABASE IF EXISTS GESTION_LIVRE;

CREATE DATABASE GESTION_LIVRE;

USE GESTION_LIVRE;

CREATE TABLE LIVRE (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	AUTEUR VARCHAR(100) NOT NULL,
	TITRE VARCHAR(100) NOT NULL,
	NB_PAGE INTEGER NOT NULL
);


SELECT * FROM LIVRE;